spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DigitalLibrary?currentSchema=digital_library
    driverClassName: org.postgresql.Driver
    username: digital_library_user
    password: digital_library_user